### ISSUE TITLE
Find a way to stop depending on jose

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-auth#10]
1. their import system is broken (see https://github.com/panva/jose/pull/202) so we're forced to depend on a fork (https://github.com/inrupt/jose-legacy-modules-js)
2. this lib do much more than what we need, let's get only the part we need

**Comment by rom1504** [comment]
actually depending on https://github.com/inrupt/jose-legacy-modules-js was not a good work around
so we need to find a solution

**Comment by extremeheat** [comment]
Linking https://github.com/facebook/jest/issues/11750

**Comment by rom1504** [comment]
looks like this is moving forward at https://github.com/facebook/jest/issues/9771#issuecomment-927135061

**Comment by rom1504** [comment]
using jose 4 and jest 27 worked, thanks!
