### ISSUE TITLE
Tells me to sign in again after getting cache

### ISSUE THREAD

**Issue by bunningtonfoot** [PrismarineJS/prismarine-auth#106]
- [ ] The [readme](https://github.com/PrismarineJS/prismarine-auth/README.md) doesn't contain a resolution to my issue 
- [ ] The [example](https://github.com/PrismarineJS/prismarine-auth/example.js) doesn't contain a resolution to my issue 

## Versions
 - node: v21
 - prismarine-auth: 2.5.0

## issue
When I use flow to sign in to my account, I have to login once more before it can join a realm. This is an issue because It’s NOT suppose to do that, so I can’t have people linking their main account to a bot for realms anti cheat. I don’t know how to explain more but it would be nice if the TODO: part worked.

## Additional context
The caching doesn’t work, and it’s quite annoying. I’ve tried everything and I still cannot get it to read the cached tokens. 
---

**Comment by LucienHH** [comment]
Can you please share the code you are using

**Comment by LucienHH** [comment]
Why are you creating an authflow before createClient? Unless you're doing it for your own needs, creating an Authflow is handled within createClient so that could be why you're having to sign in twice. Once for your own authflow and another for the authflow  within createClient.

**Comment by bunningtonfoot** [comment]
The user links their account, and the create client is in my util file, it’s made for realm owners to link their account, and then use /connect to connect their linked account to the chosen realm. But this won’t work since I have to sign in again.

**Comment by LucienHH** [comment]
If the first authflow is your link then you need to make sure the directory match so `userDir` and `directoryPath` need to point to the same location and also the username needs to match as that is what's used to create a hash. The first argument of `Authflow` and `username` in createClient need to be the same. At the moment you're passing undefined to the authflow when it should be gamertag based on your createClient options

**Comment by bunningtonfoot** [comment]
When I link all the cache is correct but when it tells me to sign in again it remakes 2 cache files with different names and the directory’s are good, too.

**Comment by LucienHH** [comment]
Yes that's why you need to match the username identifiers in both the authflow and the createClient as explained they are used to generate a hash for the file names.

**Comment by bunningtonfoot** [comment]
I understand now, will undefined still work?

**Comment by LucienHH** [comment]
In theory yes if each user has their own directory but I'd define a username to be consistent so you can easily identify a user's cached files. You can use the userid that's also being used to define the directory

**Comment by bunningtonfoot** [comment]
Yes, each user has there own folder created with their discord id.

**Comment by LucienHH** [comment]
Ok just use that as the username param then for both authflow and createClient

**Comment by bunningtonfoot** [comment]
Omg tysm! Idk why I never tried that, I was thinking about it lol 😭
