### ISSUE TITLE
How to get login user's XUID

### ISSUE THREAD

**Issue by whes1015** [PrismarineJS/prismarine-auth#11]
- [ ] The [readme](https://github.com/PrismarineJS/prismarine-auth/README.md) doesn't contain a resolution to my issue 
- [ ] The [example](https://github.com/PrismarineJS/prismarine-auth/example.js) doesn't contain a resolution to my issue 

## Versions

 - mineflayer: #.#.#
 - server: vanilla/spigot/paper #.#.#
 - node: #.#.#

## Clear question

A clear question, with as much context as possible.
What are you building? What problem are you trying to solve?

## What did you try yet?

Did you try any method from the API?
Did you try any example? Any error from those?

## Your current code

Please put here any custom code you tried yet.

```js

/*
Some code here, replace this
*/

```

**Comment by extremeheat** [comment]
Hi, what's your objective ?

I think it was removed from the current README, but this information is returned after you do a call to `Authflow.getXboxToken`.

```ts
{
  userXUID: string,
  userHash: string,
  XSTSToken: string,
  expiresOn: number
}
```

If you need a token for minecraft bedrock, the `getMinecraftBedrockToken` method returns three JWTs which contain the xuid and other relevant minecraft data.

**Comment by whes1015** [comment]
> Hi, what's your objective ?
> 
> I think it was removed from the current README, but this information is returned after you do a call to `Authflow.getXboxToken`.
> 
> ```ts
> {
>   userXUID: string,
>   userHash: string,
>   XSTSToken: string,
>   expiresOn: number
> }
> ```
> 
> If you need a token for minecraft bedrock, the `getMinecraftBedrockToken` method returns three JWTs which contain the xuid and other relevant minecraft data.

const { Authflow } = require('prismarine-auth');

const doAuth = async() => {
    const flow = new Authflow('i@heart.mineflayer', process.cwd(), { fetchProfile: true })
    const response = await flow.getMinecraftBedrockToken()
    console.log(response)
}

doAuth()


After I change like this,still have not get the XUID from response

**Comment by extremeheat** [comment]
What do you get in the response ? For bedrock, you need to provide a seperate keypair like in the docs here - https://github.com/PrismarineJS/prismarine-auth/blob/master/examples/bedrock/deviceCode.js

If you just want the XUID you can just call `getXboxToken()` with no parameters instead of `getMinecraftBedrockToken`.

```js
const { Authflow } = require('prismarine-auth')
const flow = new Authflow()
flow.getXboxToken().then(console.log)
```

**Comment by whes1015** [comment]
> What do you get in the response ? For bedrock, you need to provide a seperate keypair like in the docs here - https://github.com/PrismarineJS/prismarine-auth/blob/master/examples/bedrock/deviceCode.js
> 
> If you just want the XUID you can just call `getXboxToken()` with no parameters instead of `getMinecraftBedrockToken`.
> 
> ```js
> const { Authflow } = require('prismarine-auth')
> const flow = new Authflow()
> flow.getXboxToken().then(console.log)
> ```
> 
> see https://github.com/PrismarineJS/prismarine-auth/blob/master/docs/API.md

I got the response like this

[msa] First time signing in. Please authenticate now:
To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code VQECNZKQ to authenticate.
[msa] Signed in as whes1015@gmail.com
eyJhbGciOiJIUzI1NiJ9.eyJ4dWlkIjoiMjUzNTQzNTE3MzU2NDM5NCIsInN1YiI6ImU5OGYxNzgxLTFlNjMtNDUwZS1iMDBjLWQ5ZDZmZTc1NjU0YiIsIm5iZiI6MTYyOTA4Mzc5OSwiYXV0aCI6IlhCT1giLCJyb2xlcyI6W10sImlzcyI6ImF1dGhlbnRpY2F0aW9uIiwiZXhwIjoxNjI5MTcwMTk5LCJpYXQiOjE2MjkwODM3OTksInBsYXRmb3JtIjoiVU5LTk9XTiIsInl1aWQiOiJjNTUyYjM0MjRhMmYyOWFhMWMyZGJiYmU2NWIzZmJiOSJ9.GSBD2FK8wrPQPga3zL5uZpgiPgjZvEG1_rsgXbH1-ps

**Comment by whes1015** [comment]
> What do you get in the response ? For bedrock, you need to provide a seperate keypair like in the docs here - https://github.com/PrismarineJS/prismarine-auth/blob/master/examples/bedrock/deviceCode.js
> 
> If you just want the XUID you can just call `getXboxToken()` with no parameters instead of `getMinecraftBedrockToken`.
> 
> ```js
> const { Authflow } = require('prismarine-auth')
> const flow = new Authflow()
> flow.getXboxToken().then(console.log)
> ```
> 
> see https://github.com/PrismarineJS/prismarine-auth/blob/master/docs/API.md

This is my code

const doAuth = async() => {
const flow =await new Authflow()
flow.getXboxToken().then(console.log)
}
                                              
doAuth()

respone

(node:224) UnhandledPromiseRejectionWarning: Error: username is required
    at new MicrosoftAuthFlow (C:\Users\whes1015\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:29:26)
    at doAuth (C:\Users\whes1015\Desktop\discordbot\index.js:124:63)
    at C:\Users\whes1015\Desktop\discordbot\index.js:128:47
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by extremeheat** [comment]
Please specify a username and caching dir for now until the master branch is released on npm
```js
const { Authflow } = require('prismarine-auth')
const flow = new Authflow('username', './')
flow.getXboxToken().then(console.log)
```

**Comment by whes1015** [comment]
> Please specify a username and caching dir for now until the master branch is released on npm
> 
> ```js
> const { Authflow } = require('prismarine-auth')
> const flow = new Authflow('username', './')
> flow.getXboxToken().then(console.log)
> ```

I didn't get any response

**Comment by whes1015** [comment]
> Please specify a username and caching dir for now until the master branch is released on npm
> 
> ```js
> const { Authflow } = require('prismarine-auth')
> const flow = new Authflow('username', './')
> flow.getXboxToken().then(console.log)
> ```

![image](https://user-images.githubusercontent.com/44525760/129522335-0cd3ed02-18fd-423e-a7e4-5d6686c0de4f.png)

**Comment by whes1015** [comment]
> 請暫時指定用戶名和緩存目錄，直到在 npm 上發布 master 分支
> 
> ```js
> const  { Authflow }  =  require ( 'prismarine-auth' ) 
> const  flow  =  new  Authflow ( 'username' ,  './' ) 
> flow 。獲取XboxToken ( ) 。然後（控制台。日誌）
> ```

(node:2172) UnhandledPromiseRejectionWarning: XboxReplayError: Could not exchange "userToken", please double check the specified "XSTSRelyingParty" or refer to https://bit.ly/xr-xbl-auth-user-token-issue
    at Object.internal (C:\Users\whes1015\node_modules\@xboxreplay\errors\dist\index.js:33:77)
    at C:\Users\whes1015\node_modules\prismarine-auth\node_modules\@xboxreplay\xboxlive-auth\dist\core\xboxlive\index.js:76:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async XboxTokenManager.getXSTSToken (C:\Users\whes1015\node_modules\prismarine-auth\src\TokenManagers\XboxTokenManager.js:149:18)
    at async retry.msa.forceRefresh (C:\Users\whes1015\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:130:24)
    at async retry (C:\Users\whes1015\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:22:14)
    at async MicrosoftAuthFlow.getXboxToken (C:\Users\whes1015\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:120:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:2172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[msa] First time signing in. Please authenticate now:
To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code 9JL2QUBP to authenticate.

**Comment by extremeheat** [comment]
This is fixed in #13. Try:

npm i prismarinejs/prismarine-auth#docs

then see if you get the same error

**Comment by whes1015** [comment]
> npm iprismarinejs/prismarine-auth#docs

I got the response like this

[msa] First time signing in. Please authenticate now:
To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code YDLLJVFZ to authenticate.
[msa] Signed in as whes1015@gmail.com
[msa] First time signing in. Please authenticate now:
To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code BRA2AG8H to authenticate.

code

const doAuth = async () => {

const flow = await new Authflow('whes1015@gmail.com', './caches/')
flow.getXboxToken().then(console.log)

}

doAuth()

**Comment by whes1015** [comment]
> 這已在[＃13中](https://github.com/PrismarineJS/prismarine-auth/pull/13)修復。嘗試：
> 
> npm iprismarinejs/prismarine-auth#docs
> 
> 然後看看你是否得到同樣的錯誤

I was asked to log in twice and got the same reply

[msa] First time signing in. Please authenticate now:
To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code YDLLJVFZ to authenticate.
[msa] Signed in as whes1015@gmail.com
[msa] First time signing in. Please authenticate now:
To sign in, use a web browser to open the page https://www.microsoft.com/link and enter the code BRA2AG8H to authenticate.
[msa] Signed in as whes1015@gmail.com
(node:508) UnhandledPromiseRejectionWarning: XboxReplayError: Could not exchange "userToken", please double check the specified "XSTSRelyingParty" or refer to https://bit.ly/xr-xbl-auth-user-token-issue
    at Object.internal (C:\Users\whes1015\node_modules\@xboxreplay\errors\dist\index.js:33:77)
    at C:\Users\whes1015\node_modules\prismarine-auth\node_modules\@xboxreplay\xboxlive-auth\dist\core\xboxlive\index.js:76:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async XboxTokenManager.getXSTSToken (C:\Users\whes1015\node_modules\prismarine-auth\src\TokenManagers\XboxTokenManager.js:149:18)
    at async retry.msa.forceRefresh (C:\Users\whes1015\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:130:24)
    at async retry (C:\Users\whes1015\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:22:14)
    at async MicrosoftAuthFlow.getXboxToken (C:\Users\whes1015\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:120:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by whes1015** [comment]
> 這已在[#13 中](https://github.com/PrismarineJS/prismarine-auth/pull/13)修復。嘗試：
> 
> npm iprismarinejs/prismarine-auth#docs
> 
> 然後看看你是否得到同樣的錯誤

I just want XUID, is there any other way to get it? I just want XUID,thanks

**Comment by extremeheat** [comment]
This is not a support forum, please discuss [on Discord](https://discord.gg/GsEFRM8). You need to install it from git to get the latest update which fixes your issue.

```js
npm install prismarinejs/prismarine-auth
```
