### ISSUE TITLE
Release new version so mineflayer can be updated to support bun

### ISSUE THREAD

**Issue by TatoExp** [PrismarineJS/prismarine-auth#114]
Jose was removed in https://github.com/PrismarineJS/prismarine-auth/pull/103

Is there anything stopping a new version release so that bun can be used with mineflayer?

## current workaround

This snippet in projects package.json currently makes mineflayer work with bun

```json
"resolutions": {
  "prismarine-auth": "https://github.com/PrismarineJS/prismarine-auth.git#e70f42e"
}
```

**Comment by extremeheat** [comment]
Done
