### ISSUE TITLE
Using recursive in fs.rmdir triggers deprecation notice.

### ISSUE THREAD

**Issue by Kashalls** [PrismarineJS/prismarine-auth#14]
https://github.com/PrismarineJS/prismarine-auth/blob/0223a23039242068b11cd99a6ade184034d539d8/src/MicrosoftAuthFlow.js#L75

since v14.14.0 In future versions of Node.js and will trigger a warning fs.rmdir(path, { recursive: true }) will throw if path does not exist or is a file. Use fs.rm(path, { recursive: true, force: true }) instead.

See history: https://nodejs.org/api/fs.html#fs_fspromises_rmdir_path_options

**Comment by extremeheat** [comment]
Can you fix it?
