### ISSUE TITLE
When using `doSisuAuth` cached token is never returned.

### ISSUE THREAD

**Issue by LucienHH** [PrismarineJS/prismarine-auth#27]
## Detailed description of a problem
Currently when using `doSisuAuth` the `verifyTokens` function in XboxTokenManager will always return false thus forcing a token refresh on every call, this is because of the follwing snippet of code
```js
const ut = await this.getCachedUserToken()
const xt = await this.getCachedXstsToken()
if (!ut || !xt || this.forceRefresh) {
  return false
}
```
Sisu auth flow doesn't generate a userToken because userToken, deviceToken and titleToken are all returned in the sisu response however we only cache the xsts token.

## Expected behavior
When using `doSisuAuth` return the cached XSTS token instead of refreshing.

## Additional context
Ideally, we need to cache the returned tokens from sisu and have a solution that uses all available tokens in the cache to generate an xsts token after the current one expires as well as change the verifyTokens function to check all tokens

---

**Comment by extremeheat** [comment]
Is this still an issue? I think you mentioned caching more data at some point.

**Comment by LucienHH** [comment]
Still an issue, I'll open a pr to fix just this
