### ISSUE TITLE
Misleading error description

### ISSUE THREAD

**Issue by dement6d** [PrismarineJS/prismarine-auth#57]
- [x] The [readme](https://github.com/PrismarineJS/prismarine-auth/README.md) doesn't contain a resolution to my issue 
- [x] The [example](https://github.com/PrismarineJS/prismarine-auth/example.js) doesn't contain a resolution to my issue 

## Versions
 - node: 16.15.0
 - prismarine-auth: ^1.7.0

## Detailed description of a problem
If an account fails to login due to suspicious activities (happens when logging in from new IP's, etc.), this error is thrown: `XboxReplayError: Invalid credentials.` even though the credentials are correct

**Comment by LucienHH** [comment]
This is unrelated to prismarine-auth due to xboxlive-auth being used for password authentication which is where the error is thrown. The flow itself isn't ideal and would benefit from being added internally allowing for better error & 2FA handling.

**Comment by dement6d** [comment]
alright, ill open an issue about it there just to make it known at least
